// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskMaster.Data;

#nullable disable

namespace TaskMaster.Migrations
{
    [DbContext(typeof(TaskMasterDbContext))]
    [Migration("20240914223808_insertInitialRecords")]
    partial class insertInitialRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TaskMaster.Models.UserTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UserTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Descrição da tarefa 1",
                            DueDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Alta",
                            Status = "Não Iniciata",
                            Title = "Tarefa 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Descrição da tarefa 2",
                            DueDate = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Média",
                            Status = "Em Progresso",
                            Title = "Tarefa 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Descrição da tarefa 3",
                            DueDate = new DateTime(2024, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Baixa",
                            Status = "Concluída",
                            Title = "Tarefa 3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Descrição da tarefa 4",
                            DueDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Alta",
                            Status = "Não Iniciada",
                            Title = "Tarefa 4"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Descrição da tarefa 5",
                            DueDate = new DateTime(2024, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Média",
                            Status = "Em Progresso",
                            Title = "Tarefa 5"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Descrição da tarefa 6",
                            DueDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Alta",
                            Status = "Concluída",
                            Title = "Tarefa 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
