// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskMaster.Data;

#nullable disable

namespace TaskMaster.Migrations
{
    [DbContext(typeof(TaskMasterDbContext))]
    partial class TaskMasterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TaskMaster.Models.UserTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UserTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Descrição da tarefa 1",
                            DueDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Alta",
                            Status = "Não Iniciata",
                            Title = "Tarefa 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Descrição da tarefa 2",
                            DueDate = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Média",
                            Status = "Em Progresso",
                            Title = "Tarefa 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Descrição da tarefa 3",
                            DueDate = new DateTime(2024, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Baixa",
                            Status = "Concluída",
                            Title = "Tarefa 3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Descrição da tarefa 4",
                            DueDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Alta",
                            Status = "Não Iniciada",
                            Title = "Tarefa 4"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Descrição da tarefa 5",
                            DueDate = new DateTime(2024, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Média",
                            Status = "Em Progresso",
                            Title = "Tarefa 5"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Descrição da tarefa 6",
                            DueDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Alta",
                            Status = "Não Iniciata",
                            Title = "Tarefa 6"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Tarefa vencendo hoje 1",
                            DueDate = new DateTime(2024, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Priority = "Alta",
                            Status = "Pendente",
                            Title = "Tarefa 7"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Tarefa vencendo hoje 2",
                            DueDate = new DateTime(2024, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Priority = "Média",
                            Status = "Em Progresso",
                            Title = "Tarefa 8"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Tarefa vencendo amanhã 1",
                            DueDate = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Priority = "Baixa",
                            Status = "Pendente",
                            Title = "Tarefa 9"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Tarefa vencendo amanhã 2",
                            DueDate = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Priority = "Alta",
                            Status = "Em Progresso",
                            Title = "Tarefa 10"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Tarefa vencendo esta semana 1",
                            DueDate = new DateTime(2024, 9, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Priority = "Média",
                            Status = "Pendente",
                            Title = "Tarefa 11"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Tarefa vencendo esta semana 2",
                            DueDate = new DateTime(2024, 9, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Priority = "Baixa",
                            Status = "Não Iniciada",
                            Title = "Tarefa 12"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Tarefa vencendo esta semana 3",
                            DueDate = new DateTime(2024, 9, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Priority = "Alta",
                            Status = "Em Progresso",
                            Title = "Tarefa 13"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Tarefa vencendo esta semana 4",
                            DueDate = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Priority = "Média",
                            Status = "Pendente",
                            Title = "Tarefa 14"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Tarefa vencendo esta semana 5",
                            DueDate = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Priority = "Baixa",
                            Status = "Concluída",
                            Title = "Tarefa 15"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
